local colors = require('base46').get_theme_tb('base_30')

return {
  DevIconDefault = { fg = colors.red, bg = 'none' },
  DevIconc = { fg = colors.blue, bg = 'none' },
  DevIconcss = { fg = colors.blue, bg = 'none' },
  DevIcondeb = { fg = colors.cyan, bg = 'none' },
  DevIconDockerfile = { fg = colors.cyan, bg = 'none' },
  DevIconhtml = { fg = colors.baby_pink, bg = 'none' },
  DevIconjpeg = { fg = colors.dark_purple, bg = 'none' },
  DevIconjpg = { fg = colors.dark_purple, bg = 'none' },
  DevIconjs = { fg = colors.sun, bg = 'none' },
  DevIconkt = { fg = colors.orange, bg = 'none' },
  DevIconlock = { fg = colors.red, bg = 'none' },
  DevIconlua = { fg = colors.blue, bg = 'none' },
  DevIconmp3 = { fg = colors.white, bg = 'none' },
  DevIconmp4 = { fg = colors.white, bg = 'none' },
  DevIconout = { fg = colors.white, bg = 'none' },
  DevIconpng = { fg = colors.dark_purple, bg = 'none' },
  DevIconpy = { fg = colors.cyan, bg = 'none' },
  DevIcontoml = { fg = colors.blue, bg = 'none' },
  DevIconts = { fg = colors.teal, bg = 'none' },
  DevIconttf = { fg = colors.white, bg = 'none' },
  DevIconrb = { fg = colors.pink, bg = 'none' },
  DevIconrpm = { fg = colors.orange, bg = 'none' },
  DevIconvue = { fg = colors.vibrant_green, bg = 'none' },
  DevIconwoff = { fg = colors.white, bg = 'none' },
  DevIconwoff2 = { fg = colors.white, bg = 'none' },
  DevIconxz = { fg = colors.sun, bg = 'none' },
  DevIconzip = { fg = colors.sun, bg = 'none' },
  DevIconZig = { fg = colors.orange, bg = 'none' },
}
