local base46 = require('oxygen.base46')
local colors = base46.get_theme_tb('base_30')
local theme = base46.get_theme_tb('base_16')

local highlights = {
  MatchWord = { bg = colors.grey, fg = colors.white },
  MatchParen = { link = 'MatchWord' },
  lCursor = { fg = theme.base00, bg = theme.base05 },
  CursorIM = { fg = theme.base00, bg = theme.base05 },
  Cursor = { fg = theme.base00, bg = theme.base05 },
  CursorColumn = { bg = theme.base01, sp = 'none' },
  CursorLine = { bg = 'none', sp = 'none' },
  CursorLineNr = { fg = colors.white },
  Pmenu = { bg = colors.darker_black },
  WinBar = { link = 'Normal' },
  WinBarNC = { link = 'Normal' },
  PmenuSbar = { bg = colors.black2 },
  PmenuSel = { bg = colors.pmenu_bg, fg = colors.black },
  PmenuThumb = { bg = colors.line },
  Comment = { fg = colors.grey_fg },
  LineNr = { fg = colors.grey },
  FloatBorder = { fg = colors.line },
  VertSplit = { link = 'WinSeparator' },
  WinSeparator = { fg = colors.line },
  NormalFloat = { link = 'Normal' },
  Normal = { fg = colors.white, bg = colors.black },
  SpellBad = { undercurl = true, sp = theme.base08 },
  SpellLocal = { undercurl = true, sp = theme.base0C },
  SpellCap = { undercurl = true, sp = theme.base0D },
  SpellRare = { undercurl = true, sp = theme.base0E },
  Error = { fg = colors.red },
  ErrorMsg = { link = 'Error' },
  Exception = { link = 'Error' },
  NvimInternalError = { link = 'Error' },
  WarningMsg = { fg = colors.orange },
  MsgArea = { fg = colors.white },
  ModeMsg = { fg = theme.base0B },
  MoreMsg = { fg = theme.base0D },
  SignColumn = { bg = theme.base00, fg = theme.base03, sp = 'none' },
  ColorColumn = { bg = theme.base00, sp = 'none' },
  FoldColumn = { bg = theme.base00, fg = theme.base03, sp = 'none' },
  Visual = { bg = theme.base01 },
  VisualNOS = { fg = theme.base08 },
  Debug = { fg = theme.base08 },
  Directory = { fg = theme.base0D },
  Folded = { bg = theme.base01 },
  Macro = { fg = theme.base08 },
  Search = { fg = theme.base01, bg = theme.base0A },
  IncSearch = { fg = theme.base01, bg = theme.base09 },
  CurSearch = { link = 'IncSearch' },
  Substitute = { fg = theme.base01, bg = theme.base0A, sp = 'none' },
  Question = { fg = theme.base0D },
  SpecialKey = { fg = theme.base03 },
  TooLong = { fg = theme.base08 },
  WildMenu = { fg = theme.base08, bg = theme.base0A },
  Title = { fg = theme.base0D, sp = 'none' },
  Conceal = { bg = 'none' },
  NonText = { fg = theme.base03 },
  QuickFixLine = { bg = theme.base01, sp = 'none' },
  healthSuccess = { bg = colors.green, fg = colors.black },
}

highlights = table.merge(highlights, config.ui.highlights.add)

return highlights
